name: Prod Pipeline

on:
  push:
    branches: [ prod_test ]
  # workflow_dispatch:

jobs:
  prod:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Databricks CLI
        run: |
          curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh

      - name: Configure Databricks auth
        run: |
          echo "DATABRICKS_HOST=${{ secrets.DATABRICKS_HOST }}" >> $GITHUB_ENV
          echo "DATABRICKS_TOKEN=${{ secrets.DATABRICKS_TOKEN }}" >> $GITHUB_ENV

      - name: Validate bundle
        run: databricks bundle validate

      - name: Deploy bundle
        run: databricks bundle deploy -t prod

      - name: Deploy Model
        run: databricks bundle run prod_deploy -t prod

      # - name: Batch Inference (test)
      #   run: databricks bundle run prod_batch_test -t prod

      # - name: Wait 1 minutes
      #   run:  sleep 60

      # - name: Batch Inference (train)
      #   run: databricks bundle run prod_batch_train -t prod
      
      # - name: Wait 1 minutes
      #   run:  sleep 60

      # - name: Batch Inference (val)
      #   run: databricks bundle run prod_batch_val -t prod

      # - name: Deploy remaining model
      #   run:  databricks bundle run prod_deploy_remaining -t prod 
